FileVersion = 1
Dependencies = {corlib = "*", Beefy2D = "*", libgit2 = "*"}

[Project]
Name = "BeefLsp"
StartupObject = "BeefLsp.Program"
ProcessorMacros = ["CLI"]

[Configs.Debug.Win64]
TargetDirectory = "$(WorkspaceDir)/../IDE/dist"
TargetName = "$(ProjectName)_d"
OtherLinkFlags = "$(LinkFlags) Comdlg32.lib kernel32.lib user32.lib advapi32.lib shell32.lib IDEHelper64_d.lib Rpcrt4.lib Ole32.lib"
CLibType = "Dynamic"
BeefLibType = "DynamicDebug"
DebugCommandArguments = "--port=5556"

[Configs.Debug.Linux64]
TargetDirectory = "$(WorkspaceDir)/../IDE/dist"
TargetName = "$(ProjectName)_d"
OtherLinkFlags = "$(LinkFlags) libIDEHelper_d.so libBeefySysLib_d.so $(Var IDEHelper_libs_d)"
CLibType = "Dynamic"
BeefLibType = "DynamicDebug"
PreBuildCmds = ["ReadFile(\"$(WorkspaceDir)/../IDE/dist/IDEHelper_libs_d.txt\", \"IDEHelper_libs_d\")"]
DebugCommandArguments = "--port=5556"

[Configs.Release.Win64]
TargetDirectory = "$(WorkspaceDir)/../IDE/dist"
OtherLinkFlags = "$(LinkFlags) Comdlg32.lib kernel32.lib user32.lib advapi32.lib shell32.lib IDEHelper64.lib"
CLibType = "Dynamic"
DebugCommandArguments = "--port=5556"

[Configs.Release.Linux64]
TargetDirectory = "$(WorkspaceDir)/../IDE/dist"
OtherLinkFlags = "$(LinkFlags) libIDEHelper.so libBeefySysLib.so $(Var IDEHelper_libs)"
CLibType = "Dynamic"
PreBuildCmds = ["ReadFile(\"$(WorkspaceDir)/../IDE/dist/IDEHelper_libs.txt\", \"IDEHelper_libs\")"]
DebugCommandArguments = "--port=5556"

[[ProjectFolder.Items]]
Type = "Folder"
Path = "../IDE/src"
Name = "ide"
AutoInclude = true
